disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument

excluded:
  - Carthage
  - Pods
  - AutoChatTests
  - AutoChatUITests

line_length:
  warning: 120
  error: 200
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

force_cast: warning
force_try: warning

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - URL
    - x
    - y